from pathlib import Path
import json,html,collections,subprocess
from reportlab.platypus import BaseDocTemplate,PageTemplate,Frame,Paragraph,Spacer,PageBreak,Table,TableStyle,KeepTogether,Image
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.graphics.shapes import Drawing,Rect,String,Line,Polygon
P=Path(__file__).resolve().parents[1]; O=P/'docs/pdf';O.mkdir(parents=True,exist_ok=True)
for name,f in [('Text','DejaVuSans.ttf'),('Bold','DejaVuSans-Bold.ttf'),('Mono','DejaVuSansMono.ttf')]:
 path=Path('/usr/share/fonts/truetype/dejavu')/f
 if path.exists():pdfmetrics.registerFont(TTFont(name,str(path)))
FONT='Text' if 'Text' in pdfmetrics.getRegisteredFontNames() else 'Helvetica';BOLD='Bold' if 'Bold' in pdfmetrics.getRegisteredFontNames() else 'Helvetica-Bold'
NAVY=colors.HexColor('#102b46');TEAL=colors.HexColor('#087f76');GRAY=colors.HexColor('#52677e');LIGHT=colors.HexColor('#eaf0f6')
W=504
styles={
 'body':ParagraphStyle('body',fontName=FONT,fontSize=9.4,leading=14,spaceAfter=8,textColor=NAVY),
 'small':ParagraphStyle('small',fontName=FONT,fontSize=8,leading=11,spaceAfter=5,textColor=GRAY),
 'h1':ParagraphStyle('h1',fontName=BOLD,fontSize=18,leading=23,spaceBefore=10,spaceAfter=13,textColor=NAVY,keepWithNext=True),
 'h2':ParagraphStyle('h2',fontName=BOLD,fontSize=12,leading=17,spaceBefore=12,spaceAfter=8,textColor=TEAL,keepWithNext=True),
 'cover':ParagraphStyle('cover',fontName=BOLD,fontSize=34,leading=42,spaceAfter=20,textColor=NAVY),
 'table':ParagraphStyle('table',fontName=FONT,fontSize=8,leading=11,textColor=NAVY),
 'white':ParagraphStyle('white',fontName=BOLD,fontSize=8,leading=11,textColor=colors.white),
 'code':ParagraphStyle('code',fontName='Mono' if 'Mono' in pdfmetrics.getRegisteredFontNames() else 'Courier',fontSize=8,leading=12,backColor=LIGHT,borderPadding=8,spaceAfter=10),
}
styles['coverSub']=ParagraphStyle('coverSub',parent=styles['h1'])
styles['coverName']=ParagraphStyle('coverName',parent=styles['h2'])
styles['indexTitle']=ParagraphStyle('indexTitle',parent=styles['h1'])
def para(s,style='body'):return Paragraph(html.escape(str(s)).replace('\n','<br/>'),styles[style])
class PDF(BaseDocTemplate):
 def __init__(self,path,title):
  super().__init__(str(path),pagesize=(612,792),leftMargin=54,rightMargin=54,topMargin=53,bottomMargin=48,title=title,author='Erick Estuardo Cruz Romero - asistencia declarada de ChatGPT/Codex')
  self.docTitle=title;self.addPageTemplates(PageTemplate(id='all',frames=[Frame(54,48,W,691,id='main',leftPadding=0,rightPadding=0,topPadding=0,bottomPadding=0)],onPage=self.decorate))
 def decorate(self,c,d):
  c.saveState();c.setFillColor(TEAL);c.rect(0,778,612,14,fill=1,stroke=0)
  c.setFillColor(GRAY);c.setFont(FONT,7.3);c.drawString(54,758,'RESERVALAB  /  ASEGURAMIENTO DE LA CALIDAD DE SOFTWARE 2026')
  c.setStrokeColor(colors.HexColor('#d5dfe8'));c.line(54,38,558,38);c.setFont(FONT,7.1);c.drawString(54,26,'ERICK ESTUARDO CRUZ ROMERO  ·  0900-19-1362');c.drawRightString(558,26,str(d.page));c.restoreState()
 def afterFlowable(self,f):
  if isinstance(f,Paragraph) and f.style.name in ['h1','h2']:
   level=0 if f.style.name=='h1' else 1;text=f.getPlainText();key='h-'+str(self.seq.nextf('heading'));self.canv.bookmarkPage(key);self.notify('TOCEntry',(level,text,self.page,key))
class Doc:
 def __init__(self,file,title,subtitle,status='Documento técnico - ejecución local verificada'):
  self.file=file;self.title=title;self.story=[];self.md=['# '+title,'',subtitle,'',status,'']
  self.story += [Spacer(1,42),para('UNIVERSIDAD MARIANO GÁLVEZ DE GUATEMALA','small'),para('Facultad de Ingeniería en Sistemas de Información y Ciencias de la Computación','body'),Spacer(1,45),para('ReservaLab','cover'),para(title,'coverSub'),para(subtitle),Spacer(1,36),para('ERICK ESTUARDO CRUZ ROMERO','coverName'),para('Carné: 0900-19-1362\nCatedrático: Ing. Michael Rodolfo Asturias López\nCurso: Aseguramiento de la Calidad de Software\nSegundo semestre de 2026'),Spacer(1,30),para(status),para('Preparación: 25 de septiembre de 2026. El estado de cada evidencia se declara dentro del documento.','small'),PageBreak()]
  self.story.append(para('Índice','indexTitle'));toc=TableOfContents();toc.levelStyles=[ParagraphStyle('toc0',fontName=FONT,fontSize=10,leading=16,leftIndent=0,firstLineIndent=0,spaceBefore=6),ParagraphStyle('toc1',fontName=FONT,fontSize=8.5,leading=12,leftIndent=14,firstLineIndent=0)];self.story.extend([toc,PageBreak()])
 def h(self,s,level=1,new=False):
  if new:self.story.append(PageBreak())
  self.story.append(para(s,'h1' if level==1 else 'h2'));self.md.extend(['#'*(level+1)+' '+s,''])
 def p(self,s):self.story.append(para(s));self.md.extend([s,''])
 def bullet(self,s):self.p('• '+s)
 def code(self,s):self.story.append(para(s,'code'));self.md.extend(['```',s,'```',''])
 def table(self,headers,rows,widths=None):
  table=Table([[para(x,'white') for x in headers]]+[[para(x,'table') for x in row] for row in rows],colWidths=widths,repeatRows=1,hAlign='LEFT')
  table.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,LIGHT]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8),('LINEBELOW',(0,0),(-1,-1),.3,colors.HexColor('#d6e0e9'))]));self.story.extend([table,Spacer(1,10)]);self.md.extend(['| '+' | '.join(headers)+' |','|'+'---|'*len(headers)]+['| '+' | '.join(str(x).replace('\n','; ') for x in row)+' |' for row in rows]+[''])
 def img(self,path,width=504):
  from PIL import Image as PILImage
  im=PILImage.open(path);w,h=im.size;self.story.extend([Image(str(path),width=width,height=width*h/w),Spacer(1,10)])
 def done(self):PDF(O/self.file,self.title).multiBuild(self.story);(P/'docs'/self.file.replace('.pdf','.md')).write_text('\n'.join(self.md),encoding='utf8');print(self.file)

def box(d,x,y,w,h,title,lines):
 d.add(Rect(x,y,w,h,rx=7,ry=7,fillColor=LIGHT,strokeColor=colors.HexColor('#9bb0c4')));d.add(String(x+10,y+h-20,title,fontName=BOLD,fontSize=9,fillColor=NAVY))
 for i,line in enumerate(lines):d.add(String(x+10,y+h-37-i*13,line,fontName=FONT,fontSize=7.6,fillColor=GRAY))
def arrow(d,x1,y1,x2,y2,label=''):
 d.add(Line(x1,y1,x2,y2,strokeColor=TEAL,strokeWidth=1.3));
 if x2>x1:d.add(Polygon([x2,y2,x2-6,y2+3,x2-6,y2-3],fillColor=TEAL,strokeColor=TEAL))
 elif y2<y1:d.add(Polygon([x2,y2,x2-3,y2+6,x2+3,y2+6],fillColor=TEAL,strokeColor=TEAL))
 if label:d.add(String((x1+x2)/2+3,(y1+y2)/2+7,label,fontName=FONT,fontSize=7,fillColor=TEAL))
def diagram(kind):
 if kind=='context':
  d=Drawing(W,210);box(d,0,127,140,65,'Estudiante',['Consulta y solicita','Cancela sus reservas']);box(d,0,15,140,75,'Administrador',['Gestiona equipos','Aprueba y presta','Registra devoluciones']);box(d,267,57,225,105,'Sistema ReservaLab',['Aplicación web cliente-servidor','Usuarios, equipos y reservas','Control de disponibilidad','Historial de operaciones']);arrow(d,140,155,267,128,'HTTP');arrow(d,140,52,267,92,'HTTP');return d
 if kind=='containers':
  d=Drawing(W,250);box(d,0,133,145,94,'Frontend React / Vite',['Interfaz y formularios','Validación de presentación','Despliegue estático']);box(d,200,133,165,94,'Backend Node / Express',['API /api/* y autorización','Reglas y transacciones','Proceso independiente']);box(d,200,0,240,88,'Base de datos PostgreSQL',['Cloud: PostgreSQL persistente externo','Local: PGlite en disco','Usuarios, sesiones, reservas y auditoría']);arrow(d,145,182,200,182,'JSON');arrow(d,282,133,282,88,'SQL');return d
 d=Drawing(W,350);box(d,170,238,166,100,'users',['PK id; UNIQUE email','name, password_hash','role']);box(d,0,10,150,123,'sessions',['PK token_hash','FK user_id → users','expires']);box(d,174,10,164,157,'reservations',['PK id','FK user_id → users','FK equipment_id → equipment','start, end, purpose','status, created_at','returned_at, late_minutes']);box(d,354,238,150,100,'equipment',['PK id; UNIQUE code','name, category','description, status']);box(d,354,10,150,123,'audit',['PK id; FK user_id','action, entity_id','created_at']);arrow(d,215,238,70,133,'1:N');arrow(d,255,238,255,167,'1:N');arrow(d,335,273,430,133,'1:N');arrow(d,424,238,337,167,'1:N');return d

cases=json.loads((P/'qa/casos-completos.json').read_text());bugs=json.loads((P/'qa/defectos.json').read_text());initial=json.loads((P/'qa/evidencias/funcionales-inicial.json').read_text());final=json.loads((P/'qa/evidencias/funcionales.json').read_text());units=json.loads((P/'qa/evidencias/unitarias.json').read_text());api=json.loads((P/'qa/evidencias/api-newman.json').read_text());coverage=json.loads((P/'coverage/coverage-summary.json').read_text());audit0=json.loads((P/'qa/evidencias/dependencias-audit.json').read_text());audit1=json.loads((P/'qa/evidencias/dependencias-audit-final.json').read_text())
rf=[('RF-01','Registro de estudiantes','Crear cuenta STUDENT con nombre de 2-80 caracteres, correo único de hasta 120 y contraseña de 10-128 con mayúscula, minúscula y número. El cliente no puede elegir ADMIN.'),('RF-02','Autenticación y cierre','Validar credenciales, emitir token aleatorio de 256 bits, conservar sesión por 8 horas y revocarla al cerrar sesión.'),('RF-03','Autorización','Rechazar acceso anónimo, reservar operaciones de administración para ADMIN y limitar a STUDENT la consulta/cancelación de sus propias reservas.'),('RF-04','Catálogo','Mostrar código, nombre, categoría, descripción y estado; permitir búsqueda local por nombre, código y categoría.'),('RF-05','Gestión de equipos','Crear equipos con código único y cambiar AVAILABLE, MAINTENANCE o RETIRED; bloquear mantenimiento/retiro si existen reservas aprobadas o préstamos activos.'),('RF-06','Solicitud de reserva','Registrar equipo disponible, inicio futuro hasta 30 días, duración de 1-8 horas, precisión de minutos y propósito de 10-300 caracteres.'),('RF-07','Cupo de reservas','Limitar cada usuario a tres reservas activas: REQUESTED, APPROVED y CHECKED_OUT, incluso ante solicitudes concurrentes.'),('RF-08','Decisión administrativa','Aprobar o rechazar solicitudes REQUESTED; aprobar solo antes de iniciar y mientras equipo y horario continúen disponibles.'),('RF-09','Exclusión temporal','Impedir solapamiento de intervalos aprobados o en préstamo. Intervalos [inicio,fin): terminar exactamente cuando otro inicia es válido.'),('RF-10','Cancelación','Permitir a propietario o administrador cancelar REQUESTED o APPROVED antes del inicio. Liberar cupo y horario.'),('RF-11','Entrega del equipo','Cambiar APPROVED a CHECKED_OUT solo por ADMIN, desde 15 minutos antes del inicio hasta antes del fin, y sin otro préstamo de ese equipo pendiente de devolución.'),('RF-12','Devolución','Cambiar CHECKED_OUT a RETURNED por ADMIN una sola vez; registrar fecha y retraso en minutos, redondeado hacia arriba y nunca negativo.'),('RF-13','Resumen','Consultar conteos de reservas por estado y total de equipos. Estudiante ve sus reservas; administrador ve todas.'),('RF-14','Auditoría operacional','Registrar actor, acción, entidad y fecha para creación de reserva/equipo, cambios de estado y decisiones. Restringir consulta de los últimos 100 eventos a ADMIN.')]
rnf=[('RNF-01','Rendimiento','En QA cloud, con rampa 0-50 VU en 1 min y 50 VU durante 5 min, p95 <2000 ms en catálogo y resumen; tasa de errores <1%.','CP-61','Pendiente cloud'),('RNF-02','Seguridad','100% de rutas protegidas probadas rechazan anónimos/roles no permitidos; sesión expira a 8 h; intento 11 falla con 429 tras diez errores; ninguna respuesta de identidad expone hashes.','CP-08,09,11,33,45,48,57,58','Verificado local; SCA residual separado'),('RNF-03','Consistencia','Dos aprobaciones concurrentes del mismo horario producen exactamente una aprobación; cuatro creaciones concurrentes de un usuario aceptan como máximo tres.','CP-49,52','Verificado local; repetir con PostgreSQL cloud'),('RNF-04','Persistencia','Tras cerrar y reabrir la misma base, se conserva el 100% de los campos del equipo de prueba; repetir después de reiniciar el backend cloud.','CP-62,65','Verificado local; cloud pendiente'),('RNF-05','Usabilidad y compatibilidad','Flujo login-solicitud-aprobación-historial sin errores JavaScript; sin scroll horizontal a 390 px y 1440 px; tildes del propósito conservadas.','CP-56,63','Verificado en Chromium local'),('RNF-06','Mantenibilidad','Al menos 30 pruebas unitarias entre backend/frontend, tres con dobles; líneas >=80% en alcance declarado y mejora >=20 puntos en módulos críticos de línea base.','CP-64','90 pruebas; mejora 100 pp local'),('RNF-07','Errores controlados','Cuerpo ausente, JSON inválido y carga >16 KiB producen respectivamente 400, 400 y 413 con código/mensaje, sin trazas de servidor.','CP-50,53,54','Verificado local'),('RNF-08','Despliegue y acceso','Backend y frontend se construyen por separado; dos URL HTTPS operativas y accesibles desde sesión independiente; reserva conservada después del reinicio cloud.','CP-65','Build local aprobado; cloud pendiente')]
usecases=[
('CU-01','Registrar estudiante','Visitante','No tener cuenta con ese correo.','Abrir Crear cuenta; completar nombre/correo/contraseña; enviar; el servidor valida y registra STUDENT; mostrar confirmación.','Correo duplicado: informar conflicto. Datos inválidos: indicar validación sin crear usuario.','RF-01'),
('CU-02','Iniciar y cerrar sesión','Estudiante o administrador','Cuenta existente.','Ingresar credenciales; recibir sesión; acceder al catálogo; al terminar, cerrar sesión y revocar token.','Clave incorrecta: 401. Diez errores previos: 429. Sesión vencida: solicitar ingreso nuevamente.','RF-02, RF-03'),
('CU-03','Consultar equipos','Usuario autenticado','Sesión vigente.','Abrir Equipos; revisar fichas; escribir nombre/código/categoría; ver coincidencias y estado.','Sin coincidencias: mostrar estado vacío. Error de conexión: mensaje y botón Actualizar.','RF-04'),
('CU-04','Crear y mantener equipo','Administrador','Código nuevo para alta; sin compromisos para mantenimiento/retiro.','Agregar equipo; completar datos; guardar; ver nueva ficha; elegir estado y confirmar; guardar evento.','Código duplicado: 409. Estudiante: 403. Reserva aprobada o préstamo activo: impedir mantenimiento/retiro.','RF-03, RF-05, RF-14'),
('CU-05','Solicitar reserva','Estudiante o administrador','Equipo disponible y menos de tres reservas activas.','Elegir equipo; indicar inicio, fin y propósito; validar límites; confirmar ausencia de conflicto; registrar REQUESTED e historial.','Duración/anticipación inválida: 422; cupo agotado o equipo no disponible: 409; equipo inexistente: 404.','RF-06, RF-07, RF-09, RF-14'),
('CU-06','Aprobar o rechazar solicitud','Administrador','Reserva REQUESTED.','Abrir Reservas; revisar datos; aprobar: revalidar tiempo, equipo y solapamiento dentro de transacción; guardar APPROVED. Rechazar: guardar REJECTED.','Otro actor: 403; transición inválida o conflicto de agenda: 409; rechazo sigue permitido para solicitudes vencidas.','RF-03, RF-08, RF-09, RF-14'),
('CU-07','Cancelar reserva','Propietario o administrador','REQUESTED/APPROVED y antes de iniciar.','Abrir reserva; pulsar Cancelar; confirmar; validar autorización y tiempo; cambiar a CANCELLED; liberar cupo/horario.','Otro estudiante: 403; ya inició o estado no cancelable: 409.','RF-03, RF-10, RF-14'),
('CU-08','Entregar equipo','Administrador','Reserva APPROVED; ventana de entrega válida; sin préstamo anterior abierto.','Abrir reserva; verificar entrega física; pulsar Entregar; confirmar; bloquear equipo y consultar préstamos activos; cambiar a CHECKED_OUT.','Antes de ventana o después del fin: 409; equipo aún prestado: 409 OUTSTANDING_LOAN.','RF-03, RF-11, RF-14'),
('CU-09','Registrar devolución','Administrador','Reserva CHECKED_OUT.','Recibir equipo; registrar devolución; guardar RETURNED y fecha; calcular máximo de cero y techo de (devolución-fin)/60 000; agregar historial.','Solicitud, reserva cancelada o devolución repetida: 409; actor sin permiso: 403.','RF-03, RF-12, RF-14'),
('CU-10','Consultar resumen e historial','Usuario autenticado; historial solo ADMIN','Sesión vigente y eventos opcionales.','Revisar conteos del panel; administrador abre Actividad; consultar fecha, actor, acción y entidad de los últimos 100 eventos.','Sin datos: mostrar cero/lista vacía; estudiante no puede consultar auditoría.','RF-13, RF-14')]

# 00 guía
x=Doc('00_Guia_de_inicio_y_pendientes.pdf','Guía de inicio y cierre de entrega','Instalación en Windows, archivos incluidos y pasos que requieren intervención de Erick.','Paquete técnico preparado; la entrega académica aún requiere componentes externos y personales.')
x.h('1. Qué está listo')
x.p('ReservaLab es un producto funcional generado para evaluar su calidad. El estudiante conserva la responsabilidad de revisar el trabajo, ejecutar las herramientas en sus cuentas y defender los resultados. La aplicación está separada en frontend y backend y contiene reglas de negocio suficientes para aplicar las cuatro técnicas exigidas.')
x.table(['Verificación','Resultado local'],[['Compilación','Backend y frontend completados'],['Unitarias','90 aprobadas: 65 backend y 25 frontend'],['Casos funcionales HTTP','Inicial: 57/60. Regresión: 60/60'],['Postman / Newman','24 solicitudes y 85 aserciones aprobadas'],['Navegador','Flujo principal, escritorio 1440 px y móvil 390 px, sin error JavaScript ni overflow horizontal'],['Defectos','3 funcionales cerrados; 7 fichas SCA separadas'],['Cobertura','100% de líneas en cuatro archivos del alcance. No es cobertura global.']], [155,349])
x.h('2. Primer arranque en Windows',new=True)
x.p('Instalar Node.js 24 LTS. Extraer el ZIP en una ruta corta, por ejemplo D:\\ReservaLab. Abrir PowerShell dentro de la carpeta que contiene package.json. La primera instalación necesita conexión a internet.')
x.code('powershell -ExecutionPolicy Bypass -File scripts/setup.ps1\nnpm run dev')
x.p('Abrir http://localhost:5173. Mantener la consola abierta. El API debe responder en http://localhost:3001/api/health. Para próximos arranques, usar INICIAR.cmd o npm run dev.')
x.table(['Rol','Correo','Contraseña local'],[['Administrador','admin@reservalab.test','AdminDemo2026!'],['Estudiante','alumno@reservalab.test','AlumnoDemo2026!'],['Otro estudiante','otro@reservalab.test','AlumnoDemo2026!']],[102,232,170])
x.p('Son datos ficticios. Cambiar las claves en el despliegue cloud. Recargar la página requiere volver a iniciar sesión porque el token del frontend se mantiene en memoria; los registros se conservan en la base de datos.')
x.h('3. Verificar el proyecto',2)
x.code('npm run build\nnpm run test:coverage\nnode scripts/check-coverage.mjs\nnpm run test:api\nnpm run test:functional\nnode scripts/persistence.mjs')
x.p('Las pruebas HTTP usan una base aislada en memoria y no alteran tus datos de trabajo. Las salidas JSON, XML y capturas se encuentran en qa/evidencias. El reporte visual de cobertura se abre desde coverage/index.html.')
x.h('4. Archivos del paquete',new=True)
x.table(['Ruta','Contenido'],[['docs/pdf','Siete PDF con portada, índice y paginación; bitácoras compactas de media página.'],['docs/*.md','Texto editable de los documentos y declaración de IA.'],['backend / frontend','Código fuente y pruebas unitarias.'],['qa/casos-completos.json','65 casos diseñados; fuente de la matriz.'],['qa/TestLink_Casos.xml','Casos listos para importar en una instancia TestLink.'],['qa/api','Colección Postman y ambiente local.'],['qa/carga','Escenario k6 preparado para cloud.'],['qa/evidencias','Ejecuciones locales y capturas reales.'],['.github/workflows/quality.yml','Pipeline preparado, no ejecutado en una cuenta GitHub.'],['render.yaml','Plantilla cloud para un ambiente QA.'],['ReservaLab_historial.bundle','Historial Git exportado; conserva línea base y correcciones.']], [190,314])
x.h('5. Pendientes obligatorios',new=True)
pend=[('Registro de aplicación','Presentar ReservaLab, repositorio, licencia y línea base. El plazo original de registro ya pasó; consultar al catedrático.'),('Trabajo individual','Confirmar la adaptación de E9: el texto exige revisión de PR por otro integrante. No se puede autoacreditar esa revisión.'),('Repositorio remoto','Conectar/crear GitHub, subir el historial real y dar acceso al catedrático.'),('Herramienta de pruebas','Importar casos y registrar ejecuciones/defectos en TestLink u otra herramienta admitida. Adjuntar evidencias.'),('Diez defectos de E5','Hay tres funcionales y siete SCA de tooling. Confirmar admisión de SCA; si no, completar exploración con siete defectos funcionales genuinos.'),('Cloud','Crear PostgreSQL persistente, API y frontend. Verificar URL desde sesión independiente.'),('SonarQube','Ejecutar en el servidor local de Erick; exportar estado inicial/final; corregir Blocker/Critical y aprobar Quality Gate o justificar plan.'),('CI y PR','Registrar runner, secretos/variables, protección de ramas y revisiones efectivas; conservar enlaces y logs.'),('Carga cloud','Ejecutar k6 con 50 VU sostenidos cinco minutos y completar resultados/conclusión.'),('Defensa y bitácoras','Grabar personalmente los dos videos, publicarlos en YouTube y completar reflexiones auténticas.')]
x.table(['Pendiente','Acción'],pend,[132,372])
x.h('6. Orden para terminar la fase 1',new=True)
for s in ['Arrancar ReservaLab localmente y practicar el flujo estudiante-administrador.','Confirmar con el catedrático el trabajo individual y el registro tardío.','Subir Git al repositorio remoto y completar los enlaces del registro.','Crear el despliegue público persistente; verificarlo desde otra sesión.','Importar casos en la herramienta elegida y registrar la ejecución y los hallazgos.','Resolver el requisito de diez defectos, completar bitácora y grabar video de máximo diez minutos.','Actualizar portada/enlaces/estado del informe y comprimir los documentos finales para el curso.']:x.bullet(s)
x.p('Fase 1: viernes 25 de septiembre de 2026, 23:59. Fase 2: viernes 30 de octubre de 2026, 23:59. El enunciado menciona el registro el 11 de septiembre en la sección 2.4 y el 12 en el cronograma; la discrepancia debe consultarse, sin atribuir retroactivamente un registro que no ocurrió.')
x.done()

# 01 Fase1
x=Doc('01_Fase_1_Analisis_y_resultados.pdf','Fase 1 · Análisis y resultados','E1-E8: producto, requerimientos, arquitectura, pruebas y estado real de ejecución.')
x.h('1. Registro propuesto de la aplicación')
x.table(['Campo','Información'],[['Nombre','ReservaLab'],['Origen','Aplicación generada con IA bajo especificación del estudiante; no se evalúa su construcción.'],['Responsable','ERICK ESTUARDO CRUZ ROMERO, 0900-19-1362'],['Roles','Analista de Pruebas, Ingeniero de Automatización e Ingeniero de Plataforma/DevOps, asumidos por Erick.'],['Tecnologías','React + Vite; Node.js 24 + Express; PGlite local / PostgreSQL cloud.'],['Licencia','MIT para código original; licencias de dependencias conservadas.'],['Repositorio y URL','Pendientes de publicación; no existe registro previo en el curso.'],['Línea base','Tag baseline-v0, sin pruebas automatizadas de origen; instrumentación sin tests: 0% en domain.js y rules.js.'],['Estado','Preparado para registrar, no registrado ni aprobado por el catedrático.']],[142,362])
x.h('2. E1 · Descripción y alcance',new=True)
x.p('ReservaLab apoya al laboratorio que comparte equipos entre estudiantes. Sustituye una agenda informal por solicitudes con reglas de duración y disponibilidad, aprobación administrativa, entrega y devolución. El resultado esperado del negocio es evitar comprometer un mismo equipo en horarios incompatibles y conservar quién autorizó cada operación.')
x.p('El estudiante consulta equipos, solicita horarios y cancela antes del inicio. El administrador agrega equipos, gestiona mantenimiento, aprueba/rechaza solicitudes y registra movimientos físicos. Ambos roles pueden consultar su información; solo el administrador ve todas las reservas y la auditoría.')
x.p('Alcance: un laboratorio, equipos identificables individualmente, reservas de una sola unidad, tiempos registrados como milisegundos UTC y mostrados en la zona del dispositivo. No incluye cobros, correo, facturación, geolocalización ni integración con inventarios reales. Las solicitudes vencidas no expiran automáticamente: el administrador debe rechazarlas para liberar el cupo; esta limitación está declarada.')
x.h('2.1 Reglas de negocio',2)
x.table(['Regla','Definición'],[['RB-01','Sesión de ocho horas, rol verificado en servidor.'],['RB-02','Inicio estrictamente futuro y hasta 30 días; intervalos de 1 a 8 horas; precisión de minutos.'],['RB-03','Propósito de 10 a 300 caracteres después de quitar espacios externos.'],['RB-04','Máximo tres reservas en REQUESTED, APPROVED o CHECKED_OUT por usuario.'],['RB-05','Las solicitudes pueden competir; la aprobación vuelve a verificar disponibilidad bajo transacción.'],['RB-06','[inicio,fin) permite reservas contiguas pero no solapadas.'],['RB-07','Entrega desde inicio-15 min hasta antes del fin y sin préstamo anterior sin devolver.'],['RB-08','Devolución única; retraso=max(0,ceil((devuelto-fin)/60 000)).'],['RB-09','No pasar a mantenimiento o retirado un equipo con reservas aprobadas o préstamos activos.']],[65,439])
x.h('2.2 Casos de uso principales',new=True)
for id,title,actor,pre,flow,alt,refs in usecases:
 x.h(id+' · '+title,2);x.table(['Elemento','Descripción'],[['Actor',actor],['Precondición',pre],['Flujo principal',flow],['Flujo alterno',alt],['Requerimientos',refs]],[100,404])
x.h('2.3 Requerimientos funcionales',new=True)
for id,title,text in rf:x.h(id+' · '+title,2);x.p(text)
x.h('2.4 Requerimientos no funcionales medibles',new=True)
for id,title,criterion,tests,state in rnf:x.h(id+' · '+title,2);x.p(criterion);x.p('Verificación: '+tests+'. Estado: '+state+'.')
x.h('3. E2 · Arquitectura',new=True)
x.h('3.1 Contexto',2);x.story.append(diagram('context'));x.p('Los actores interactúan con un único producto. El hosting y la base se muestran como contenedores técnicos a continuación. No existe servicio de correo ni pasarela de pago en esta versión.')
x.h('3.2 Contenedores',2);x.story.append(diagram('containers'));x.p('Frontend y backend tienen carpetas, package.json y procesos de construcción separados. Durante desarrollo se usa un proxy Vite /api hacia el proceso API. En cloud, VITE_API_URL apunta al backend HTTPS y APP_ORIGIN limita el origen permitido por CORS. La base solo es accesible al servidor.')
x.h('3.3 Modelo de datos',new=True);x.story.append(diagram('er'));x.p('Las flechas indican relaciones de uno a muchos. users.id es referenciado por sessions, reservations y audit; equipment.id por reservations. audit.entity_id identifica lógicamente equipo o reserva y no tiene una única clave foránea porque referencia dos tipos de entidad.')
x.p('El esquema se encuentra en backend/src/schema.sql. Las consultas usan parámetros $1, $2, etc. Existen índices por equipo/estado/intervalo, usuario/estado, vencimiento de sesión y fecha de auditoría. Las operaciones compuestas usan una transacción con bloqueo de las filas que protegen el cupo o la disponibilidad.')
x.h('3.4 Módulos críticos y cobertura',2)
x.table(['Componente','Impacto y verificación'],[['Políticas de reserva y transición','backend/src/domain.js. Un fallo admite horarios, permisos o cambios de estado inválidos. Cobertura unitaria medida contra baseline-v0.'],['Validación de presentación','frontend/src/rules.js. Un fallo produce formularios incoherentes o acciones indebidas en la interfaz. Cobertura unitaria medida contra baseline-v0.'],['Credenciales y cliente API','security.js y api.js. Pruebas unitarias adicionales; se conserva hash con sal, comparación segura y respuesta de error.'],['Orquestación transaccional y persistencia','app.js y db.js. Componentes de alto impacto cubiertos por integración HTTP, concurrencia y persistencia local. No están incluidos en la cifra de cobertura unitaria ni se declara cobertura global. Repetir contra PostgreSQL cloud.']],[175,329])
x.p('La mejora de 20 puntos se verifica en los dos módulos de políticas identificados para línea base. Confirmar con el catedrático si exige extender el alcance unitario a la orquestación transaccional; se declara esta limitación para evitar presentar el 100% parcial como cobertura de todos los componentes críticos.')
x.h('3.5 Dependencias y despliegue',2)
x.p('React y React DOM construyen la interfaz; Vite compila sus recursos. Express expone la API; pg accede a PostgreSQL externo; PGlite permite desarrollo local con persistencia. Vitest y V8 generan pruebas/cobertura; Newman ejecuta Postman; k6 prepara carga. Google Fonts es una dependencia visual opcional con fuentes de sistema de respaldo. El archivo package-lock.json fija las versiones instaladas.')
x.h('4. E3 · Diseño de pruebas',new=True)
x.p('Se diseñaron 65 casos: 60 funcionales HTTP y cinco verificaciones no funcionales. El catálogo completo está en 02_Casos_y_trazabilidad.pdf y en qa/casos-completos.json. Cada ficha identifica requisito, técnica, precondiciones, datos, pasos, esperado y prioridad. Se utilizaron explícitamente las cuatro técnicas exigidas.')
x.table(['Técnica','Aplicación concreta'],[['Partición de equivalencia','Correos válidos/ inválidos, existencia de equipo, acceso a catálogo, caracteres acentuados.'],['Valores límite','Duraciones 59, 60, 480 y 481 min; propósitos 9, 10, 300 y 301 caracteres; anticipación 30 días; máximo tres reservas.'],['Tabla de decisión','Actor con/sin permiso, credencial válida/inválida, disponibilidad y conflicto, préstamo anterior pendiente.'],['Transición de estados','Solicitud, aprobación/rechazo, cancelación, entrega, devolución y rechazo de transiciones inválidas.']],[142,362])
x.h('4.1 Tabla de decisión de aprobación',2)
x.table(['Regla','ADMIN','REQUESTED','Futura','Equipo libre','Sin conflicto','Resultado'],[['D1','No','-','-','-','-','403'],['D2','Sí','No','-','-','-','409 STATE'],['D3','Sí','Sí','No','-','-','409 STARTED'],['D4','Sí','Sí','Sí','No','-','409 EQUIPMENT'],['D5','Sí','Sí','Sí','Sí','No','409 CONFLICT'],['D6','Sí','Sí','Sí','Sí','Sí','200 APPROVED']],[38,47,65,42,60,61,191])
x.h('4.2 Tabla de estados',2)
x.table(['Origen','Evento','Destino','Condiciones'],[['REQUESTED','approve','APPROVED','ADMIN; futura; disponible; sin conflicto'],['REQUESTED','reject','REJECTED','ADMIN'],['REQUESTED / APPROVED','cancel','CANCELLED','Propietario o ADMIN; antes de inicio'],['APPROVED','checkout','CHECKED_OUT','ADMIN; ventana de entrega; sin préstamo anterior'],['CHECKED_OUT','return','RETURNED','ADMIN; registrar devolución única']],[114,65,96,229])
x.h('5. E4 · Trazabilidad y cobertura de requisitos',new=True)
x.p('Todos los 14 RF y 8 RNF tienen al menos un caso diseñado. Tener diseño no significa que exista ejecución: RNF-01 y RNF-08 conservan verificación cloud pendiente; persistencia y concurrencia tienen resultados locales que deben repetirse sobre el despliegue. La matriz distingue explícitamente esas situaciones.')
x.p('DEF-01 afecta RNF-07 mediante CP-50; DEF-02 afecta RF-11 mediante CP-51; DEF-03 afecta RF-05 mediante CP-59. Los tres fueron reproducidos y cerrados localmente. Los hallazgos SCA se vinculan al control de seguridad del toolchain y permanecen separados del resultado funcional.')
x.h('6. E5 · Ejecución y métricas',new=True)
x.table(['Métrica','Inicial','Regresión'],[['Casos funcionales ejecutados','60','60'],['Aprobados','57','60'],['Fallidos','3','0'],['Tasa de aprobación','95,00%','100,00%'],['Defectos funcionales distintos','3','0 abiertos / 3 cerrados'],['Entorno','Local, HTTP real, PGlite aislado','Local, mismo catálogo de casos']],[222,141,141])
x.p('Tasa de aprobación = casos aprobados / casos ejecutados ×100. El reloj se inyecta en las pruebas para verificar vencimiento, ventana de entrega y retraso sin esperar horas reales. Esta inyección solo existe en la construcción de prueba createApp; no hay endpoint que permita alterar el reloj del servidor productivo.')
x.table(['Severidad funcional','Cantidad'],[['Alta','1: DEF-02'],['Media','1: DEF-01'],['Baja','1: DEF-03']],[220,284])
x.h('6.1 Densidad de defectos por módulo',2)
modulemap={'Autenticación':['RF-01','RF-02','RNF-07'],'Equipos':['RF-04','RF-05'],'Préstamos':['RF-11','RF-12'],'Reservas':['RF-06','RF-07','RF-08','RF-09','RF-10'],'Seguridad/consistencia':['RF-03','RNF-02','RNF-03'],'Resumen/auditoría/otros':['RF-13','RF-14','RNF-05']}
rows=[]
for module,ids in modulemap.items():
 n=sum(c['requirement'] in ids for c in cases[:60]);b=sum(d['module']==module and d['type']=='Funcional' for d in bugs);rows.append([module,str(n),str(b),f'{b/n:.3f}' if n else 'N/A'])
x.table(['Módulo','Casos','Defectos','Defectos/caso'],rows,[235,60,70,139]);x.p('Se define densidad operacional como defectos funcionales distintos del módulo / casos ejecutados del módulo. No se usa KLOC ni se mezclan hallazgos de dependencias. La suma de defectos es tres; varios casos podrían apuntar al mismo defecto sin contarlo varias veces.')
x.h('6.2 Gestión en herramienta',2)
x.p('Está preparado qa/TestLink_Casos.xml con 65 casos y scripts/import-testlink.py para registrar resultados existentes mediante XML-RPC. No se tuvo acceso a una instancia TestLink durante la preparación. Por tanto, E5 no está acreditado como ejecución en herramienta profesional. Antes de entregar: crear proyecto/plan/builds, importar casos, registrar resultados, adjuntar evidencia y obtener captura del reporte de TestLink.')
x.h('6.3 Diez fichas de hallazgos y su alcance',new=True)
x.p('Se documentan tres defectos funcionales y siete hallazgos reales de análisis de dependencias (SCA). Estos últimos afectan herramientas de desarrollo, principalmente Newman, no constituyen siete fallos funcionales demostrados ni resultados de SonarQube. Su eventual aceptación para el mínimo de diez defectos de E5 debe confirmarse con el catedrático. Si exige diez defectos de ejecución de la aplicación, faltan siete; no se han fabricado defectos para llenar el número.')
for b in bugs:
 x.h(b['id']+' · '+b['title'],2);x.table(['Campo','Detalle'],[['Tipo / módulo',b['type']+' / '+b['module']],['Severidad / prioridad',b['severity']+' / '+b['priority']],['Trazabilidad',b['requirement']+' / '+b['case']],['Reproducción',b['steps']],['Esperado',b['expected']],['Obtenido',b['actual']],['Estado / solución',b['status']+'. '+b['fix']],['Evidencia',b['evidence']+(' Referencia: '+b['reference'] if b.get('reference') else '')]],[115,389])
x.h('7. E6-E8 · Estado de cierre',new=True)
x.p('E6: se entrega configuración de despliegue separado y PostgreSQL persistente; falta crear recursos y verificar una URL pública. E7: se entrega pauta de defensa, no video. E8: se entrega ficha de reflexión individual para que Erick la complete con su experiencia. Estos componentes no se marcan cumplidos por existir una plantilla.')
x.h('8. Conclusiones',2)
x.p('La regresión local confirma las 60 expectativas funcionales del catálogo. La ejecución inicial descubrió tres fallos con impacto distinto y la segunda corrida verificó sus correcciones. La separación de políticas, interfaz y persistencia permite evaluar reglas aisladas y flujos HTTP completos. Aun así, el producto no puede declararse listo para la entrega académica completa hasta integrar la herramienta de pruebas, el despliegue cloud, los requisitos de defectos, la defensa y la bitácora.')
x.h('9. Evidencias visuales',new=True)
x.img(P/'qa/evidencias/capturas/02-catalogo-admin.png',480);x.p('Captura real del catálogo en Chromium. Fuente: qa/evidencias/capturas/02-catalogo-admin.png. Datos de demostración, no inventario de una institución real.')
x.h('10. Declaración de IA y referencias',new=True)
x.p((P/'docs/ANEXO_IA.md').read_text().split('## Intervención de IA')[1].split('## Responsabilidad')[0].strip());x.p('El anexo completo se incluye en docs/ANEXO_IA.md con las solicitudes y la especificación utilizadas. El historial identifica commits de asistencia IA; no se atribuyen a trabajo manual del estudiante.')
x.p('Referencia normativa: Universidad Mariano Gálvez de Guatemala, Enunciado del Proyecto Final de Aseguramiento de la Calidad de Software 2026, 13 páginas; secciones 2-5 y 7. Documentación técnica: https://pglite.dev/docs/api ; https://vitest.dev/config/coverage ; https://learning.postman.com/docs/reference/newman-cli/installing-running-newman/ . Consulta: 25/09/2026.')
x.done()

# 02 casos y trazabilidad
x=Doc('02_Casos_y_trazabilidad.pdf','Casos de prueba y trazabilidad','65 casos diseñados, cuatro técnicas formales y estado de ejecución por requisito.')
x.h('1. Convenciones de ejecución')
x.p('T es el instante de referencia redondeado a minuto completo. Para los 60 casos HTTP se inicializa una base aislada con usuarios admin, student y other; LAB-001, 002 y 003 disponibles; LAB-004 en mantenimiento. Cada caso reinicia reservas, auditoría y sesiones, autentica las tres cuentas y luego ejecuta su escenario. Inicio normal=T+1h; fin=T+2h; propósito normal="Práctica de laboratorio". Las contraseñas son las del entorno demo, no credenciales reales.')
x.p('Una entrada rechazada correctamente es una prueba aprobada: por ejemplo, esperar 409 y recibir 409 no significa que el software tenga un defecto. Los defectos se detectan cuando el resultado obtenido difiere del esperado. El video que exige un caso fallido debe mostrar una discrepancia real, como CP-51 sobre baseline-v0, y luego explicar su corrección.')
x.table(['Estado','Significado'],[['Aprobado local','Existe salida reproducible en qa/evidencias. No implica registro ya realizado en TestLink.'],['Fallido inicial / cerrado','Se conserva la corrida inicial con el defecto y una regresión aprobada.'],['Pendiente','El diseño y script existen, pero falta ejecutar la verificación indicada.']],[125,379])
x.h('2. Matriz de trazabilidad',new=True)
rfextra={'RF-03':['CP-08','CP-11','CP-33','CP-45','CP-58'],'RF-14':['CP-44'],'RNF-02':['CP-08','CP-09','CP-11','CP-33','CP-45','CP-48','CP-57','CP-58'],'RNF-05':['CP-56','CP-63']}
rows=[]
for id,*_ in rf+rnf:
 ids=sorted(set([c['id'] for c in cases if c['requirement']==id]+rfextra.get(id,[])))
 if id=='RNF-04':ids=['CP-62','CP-65']
 mapped=[b['id'] for b in bugs if b['requirement']==id and b['type']=='Funcional']
 status='Aprobado local'
 if id in ['RNF-01','RNF-08']:status='Pendiente cloud'
 if id=='RNF-04':status='Local aprobado; cloud pendiente'
 rows.append([id,', '.join(ids),status,', '.join(mapped) or 'Sin defecto funcional'])
x.table(['Requisito','Casos asociados','Ejecución','Defectos'],rows,[65,210,124,105])
x.p('Cobertura de diseño: 22/22 requisitos (100%). Cobertura de ejecución cloud: pendiente para RNF-01 y RNF-08. La matriz es un mapa de cobertura, no una declaración de cumplimiento total. DEF-01/02/03 están cerrados localmente. Los SCA se consultan en el registro separado de defectos.')
x.h('3. Distribución por técnica',new=True)
x.table(['Técnica','Casos diseñados'],[[k,str(v)] for k,v in collections.Counter(c['technique'] for c in cases).items()],[370,134])
x.h('4. Fichas de casos',new=True)
execmap={r['id']:r for r in final['results']};before={r['id']:r for r in initial['results']}
for c in cases:
 # Each complete case starts on a page: readable and stable for print and TestLink use.
 if c['id']!='CP-01':x.story.append(PageBreak())
 x.h(c['id']+' · '+c['title'],2)
 x.table(['Campo','Detalle'],[['Requerimiento',c['requirement']],['Técnica / prioridad',c['technique']+' / '+c['priority']],['Precondiciones',c['preconditions']],['Datos de prueba',c['data']],['Pasos',c['steps']],['Resultado esperado',c['expected']]], [115,389])
 r=execmap.get(c['id'])
 if r:
  lines=[]
  for i,call in enumerate(r['requests'],1):lines.append(f"{i}. {call['method']} /api{call['path']} -> HTTP {call['status']}")
  x.p('Secuencia HTTP observada (después de preparar usuarios/sesiones):')
  x.p('\n'.join(lines))
  x.p('Inicial: '+before[c['id']]['outcome']+'. Regresión: '+r['outcome']+'. Evidencia: qa/evidencias/funcionales.json, identificador '+c['id']+'.')
  if before[c['id']]['error']:x.p('Discrepancia inicial: '+before[c['id']]['error'])
 else:x.p('Estado: '+c['status']+'. Evidencia o ruta de ejecución: '+{'CP-61':'qa/carga/reservalab.k6.js (sin resultado cloud)','CP-62':'qa/evidencias/persistencia.json','CP-63':'qa/evidencias/navegador.json y capturas','CP-64':'qa/evidencias/unitarias.json y coverage/coverage-summary.json','CP-65':'render.yaml y scripts/deploy-render.mjs (sin despliegue real)'}[c['id']]+'.')
x.done()

# 03 fase2
x=Doc('03_Fase_2_Automatizacion_y_plataforma.pdf','Fase 2 · Automatización y plataforma','E9-E16: pruebas unitarias y API, cobertura, SonarQube, pipeline, carga y defensa.','Pruebas locales ejecutadas; integración externa y carga cloud pendientes.')
x.h('1. E9 · Estrategia de ramas')
x.table(['Rama','Propósito','Promoción'],[['DEV','Integración de cambios y pruebas iniciales','feature/* -> DEV mediante PR.'],['QA','Candidato para validar en cloud y ejecutar carga','DEV -> QA después de pipeline aprobado.'],['main / PROD','Versión estable de la demostración','QA -> main después de validación, revisión y evidencias.']],[95,190,219])
x.p('Los ambientes deben tener bases y servicios separados. El workflow selecciona el ambiente por rama destino y conserva el SHA exacto al desplegar. Los secretos no se guardan en Git. Los Pull Requests ejecutan calidad pero no despliegan; un push a una rama autorizada despliega después de todas las comprobaciones.')
x.h('1.1 Reglas de protección pendientes de configurar',2)
for s in ['Proteger QA y main: exigir PR, check quality aprobado y rama actualizada.','Exigir revisión efectiva por otra persona autorizada; impedir autoaprobaciones y push directo.','Resolver todos los comentarios antes del merge y no eludir las reglas con permisos administrativos.','Conservar al menos tres PR con revisión sustantiva y evidencia de que un pipeline fallido bloquea el merge.']:x.bullet(s)
x.p('El estudiante trabaja solo. La sección E9 exige otro integrante como revisor; se debe pedir una adaptación al catedrático antes de afirmar cumplimiento. El historial entregado no contiene revisiones ficticias ni tres PR creados artificialmente.')
x.h('1.2 Tres cambios propuestos para revisión real',2)
x.table(['PR propuesto','Qué debería revisar otra persona'],[['PR-01 · Validación de entradas','Revisar DEF-01, mensajes, HTTP 400/413, contratos y regresión CP-50/53/54.'],['PR-02 · Integridad de préstamos','Examinar bloqueo transaccional, casos concurrentes y cierre de DEF-02 con CP-49/51/52.'],['PR-03 · Automatización y despliegue','Revisar orden del pipeline, Quality Gate, secretos, aislamiento y despliegue del SHA verificado.']],[160,344])
x.h('2. E10 · Pruebas unitarias',new=True)
x.p('Vitest ejecutó 90 pruebas: domain.test.js (59), security.test.js (6), rules.test.js (22) y api.test.js (3). Backend: 65; frontend: 25. Las pruebas unitarias verifican funciones y políticas aisladas; no se presentan las solicitudes de Newman ni la suite HTTP como pruebas unitarias.')
x.table(['Archivo del alcance','Líneas cubiertas','Alcance'],[[k.split('/ReservaLab/')[-1],str(v['lines']['pct'])+'%', 'Unitaria'] for k,v in coverage.items() if k!='total'],[290,100,114])
x.p('El 100% corresponde al alcance explícito de cuatro archivos: domain.js, security.js, rules.js y api.js. Quedan fuera de esa cifra app.js, db.js, server.js y main.jsx. Estos se verifican en pruebas funcionales/integración o navegador; no se afirma cobertura unitaria global.')
x.h('2.1 Línea base e incremento',2)
x.table(['Módulo base','Antes','Después','Diferencia'],[['backend/src/domain.js','0%','100%','+100 puntos'],['frontend/src/rules.js','0%','100%','+100 puntos']],[275,70,70,89])
x.p('Línea base: cero pruebas de origen, preservada en baseline-v0. El reporte base usa c8 sin ejecutar pruebas y el reporte final usa Vitest/V8; ambos se comparan por porcentaje de líneas del mismo módulo, no por igualdad de contadores físicos. La mejora comprobada supera los 20 puntos exigidos en ese alcance. La ampliación del alcance a orquestación transaccional requiere pruebas unitarias adicionales y debe acordarse si así lo interpreta el catedrático.')
x.code('npm run test:coverage\nnode scripts/check-coverage.mjs')
x.h('2.2 Dobles de prueba',2)
x.table(['Prueba','Dependencia aislada','Justificación'],[['MOCK-01','Repositorio: equipo disponible y sin conflicto','Verificar decisión de aprobación sin DB ni red.'],['MOCK-02','Repositorio: equipo en mantenimiento','Verificar rechazo y que no se consulta disponibilidad de agenda innecesariamente.'],['MOCK-03','Repositorio: conflicto existente','Verificar bloqueo por negocio sin fabricar filas en una base real.'],['MOCK-04','Repositorio que falla','Verificar propagación del error de infraestructura, sin confundirlo con una aprobación.'],['Cliente API','fetch simulado','Verificar envío de token/cuerpo y manejo de errores sin conectarse al servidor.']],[87,190,227])
x.h('3. E11 · Pruebas de API',new=True)
x.p('La colección versionada contiene 24 solicitudes y 85 aserciones automáticas de código HTTP, esquema JSON y contenido. Encadena registro, login de estudiante, reserva, login administrador, aprobación, entrega, devolución y auditoría. También cubre controles de permisos, duración, mantenimiento, duplicados y cierre de sesión.')
x.table(['Métrica','Resultado'],[['Solicitudes','24 ejecutadas / 0 fallidas'],['Aserciones','85 ejecutadas / 0 fallidas'],['Framework','Postman Collection v2.1 ejecutada por Newman'],['Base / servidor','PGlite en memoria y HTTP local en puerto efímero'],['Reporte','qa/evidencias/api-newman.json'],['Limitación','No mide rendimiento cloud y no acredita ejecución del pipeline remoto.']],[145,359])
x.code('npm run test:api')
x.p('Cada ejecución crea un entorno aislado. La colección no debe ejecutarse contra PROD porque registra usuarios, cambia estados y crea datos. Los tokens no se escriben en el reporte resumido entregado.')
x.h('4. E12 · SonarQube',new=True)
x.p('El estudiante dispone de SonarQube en http://localhost:9000. No se pudo acceder a ese servidor desde la sesión de preparación: localhost identifica cada equipo. Se entregan la configuración, el script de escaneo y el exportador de métricas; no existen aún resultados iniciales/finales de Sonar ni un Quality Gate aprobado.')
x.table(['Dato exigido por E12','Estado'],[['Bugs, vulnerabilidades, code smells','Pendiente de análisis Sonar real.'],['Duplicación y deuda técnica','Pendiente; registrar valores y unidad (deuda en minutos).'],['Blocker / Critical iniciales','Pendiente de consultar; no asignar cero por ausencia de reporte.'],['Remediación antes/después','Ejecutar, corregir hallazgos reales y comparar con evidencia.'],['Quality Gate','Configurado para esperar resultado; aprobación no verificada.']],[220,284])
x.h('4.1 Ejecutar en Windows',2)
x.p('Crear proyecto reservalab-dev y generar token. Definir SONAR_TOKEN como variable de entorno solo en la sesión. Generar cobertura. Desde la raíz del proyecto, ejecutar scripts/sonar.ps1. El scanner se ejecuta en Docker y usa host.docker.internal:9000 para acceder a Sonar en el host Windows.')
x.code('npm run test:coverage\n./scripts/sonar.ps1 -ProjectKey reservalab-dev\nnode scripts/sonar-evidence.mjs inicial')
x.p('Configurar un Quality Gate con cero Blocker/Critical abiertos, cobertura >=80% dentro del alcance acordado y duplicación <=3%, o adaptar los controles disponibles en la versión instalada. Registrar la configuración real con captura. sonar.qualitygate.wait=true hace fallar el comando si el gate no se aprueba. Si no es posible aprobarlo, adjuntar plan técnicamente justificado con responsable y fecha; no cambiar la evidencia a “aprobado”.')
x.h('4.2 Hallazgos de dependencias: medición distinta',2)
x.table(['npm audit','Inicial','Después'],[['Paquetes señalados','19','13'],['Críticos','1','0'],['Altos','11','7'],['Moderados','7','6'],['Dependencias de producción con hallazgos','No presentado como Sonar','0 en npm audit --omit=dev']],[245,129,130])
x.p('Se actualizaron handlebars, flatted, lodash y node-forge mediante overrides y se volvió a ejecutar Newman. Persisten hallazgos transitivos de herramientas de desarrollo; el reporte final los enumera. npm audit es SCA y no reemplaza E12. La ausencia de hallazgos en dependencias de producción no demuestra ausencia de vulnerabilidades en el código.')
x.h('5. E13 · Pipeline',new=True)
x.p('Archivo: .github/workflows/quality.yml. Ejecutor requerido: runner autohospedado Windows X64 en la computadora de Erick con Git, Node 24 y Docker Desktop. Esto permite acceder al SonarQube local sin exponerlo a internet. El workflow está preparado y revisado, pero no ejecutado en GitHub.')
x.table(['Orden','Paso','Condición de avance'],[['1','Compilación backend/frontend','Comandos terminan con código 0.'],['2','Vitest, cobertura y delta de línea base','90 pruebas y umbrales aprobados.'],['3','SonarQube y Quality Gate','Escaneo finaliza y gate no falla.'],['4','Newman + regresión HTTP','Colección y casos funcionales aprobados.'],['5','Despliegue de backend y frontend','Solo push; Render confirma live para el mismo SHA.']],[45,235,224])
x.p('Secretos: SONAR_TOKEN y RENDER_API_KEY. Variables por ambiente: SONAR_PROJECT_KEY, RENDER_BACKEND_ID y RENDER_FRONTEND_ID. Sonar Community puede manejar proyectos separados para DEV/QA/PROD sin asumir soporte de análisis multirrama. En cada proyecto debe configurarse el gate. El job quality debe ser obligatorio en reglas de protección de QA/main; el YAML solo no instala esas reglas.')
x.h('5.1 Cloud con persistencia',2)
x.p('La plantilla render.yaml define un API Node y un frontend estático para QA. DATABASE_URL debe apuntar a PostgreSQL persistente con TLS, por ejemplo en Neon. En el servicio gratuito de Render el sistema de archivos es efímero, de modo que PGlite local no se usa como almacenamiento cloud. Los servicios gratuitos pueden suspenderse por inactividad: medir calentamiento y carga en condiciones declaradas. Consultar límites vigentes antes de crear los ambientes.')
x.h('6. E14 · Carga',new=True)
x.table(['Elemento','Configuración'],[['Herramienta','k6, script qa/carga/reservalab.k6.js'],['Objetivo','URL HTTPS real del API QA desplegado'],['Endpoints','GET /api/equipment y GET /api/dashboard'],['Perfil','0-50 VU en 1 min; 50 VU sostenidos 5 min; descenso 30 s'],['Duración mínima programada','6 min 30 s, más setup/graceful shutdown'],['Autenticación','Una cuenta de prueba en setup; token válido de ocho horas'],['Métricas','Promedio, p95, throughput (solicitudes/segundo), tasa de error'],['Umbrales RNF-01','p95<2000 ms por endpoint y tasa de errores<1%'],['Evidencia prevista','qa/evidencias/carga-k6.json'],['Resultado actual','No ejecutado: no existe aún ambiente cloud accesible.']],[160,344])
x.code('k6 run qa/carga/reservalab.k6.js')
x.p('Antes de ejecutar, definir BASE_URL, EMAIL y PASSWORD en el entorno de la terminal. El script usa HTTPS por defecto y no contiene contraseñas. No usar ALLOW_LOCAL para acreditar E14: esa opción solo permite una comprobación técnica local, que debe declararse como tal.')
x.h('6.1 Conclusión que debe completarse con la medición',2)
x.p('Registrar fecha, región, tipo de instancia, versión del producto, calentamiento, promedio/p95 por endpoint, solicitudes totales, duración efectiva y tasa de error. Comparar cada p95 con 2000 ms y la tasa con 1%. Si falla un criterio, concluir incumplimiento de RNF-01 para ese escenario y proponer optimización o ajuste de recursos. No se incluyen números simulados ni una conclusión de cumplimiento sin ejecución.')
x.h('7. E15-E16 · Defensa y bitácora',new=True)
x.p('El PDF 04 prepara una demostración de máximo diez minutos. El estudiante debe mostrar pipeline completo en vivo, resultados de Sonar y carga, con rostro visible durante su segmento. El PDF 06 es una ficha de media página para reflexión personal, no una bitácora escrita como si el estudiante ya hubiera realizado las actividades.')
x.h('8. Estado por entregable',2)
x.table(['Entregable','Estado verificable'],[['E9','Estrategia y workflow preparados; faltan ramas/remoto, protecciones y tres revisiones externas.'],['E10','90 unitarias y cobertura local verificadas; confirmar alcance crítico y ejecutarlas en pipeline.'],['E11','24 solicitudes y 85 aserciones verificadas localmente; falta corrida en pipeline.'],['E12','Configuración preparada; medición Sonar y gate pendientes.'],['E13','Pipeline escrito; ejecución y despliegues remotos pendientes.'],['E14','Script preparado; carga cloud y conclusión pendientes.'],['E15','Pauta preparada; video pendiente.'],['E16','Ficha preparada; reflexión personal pendiente.']],[70,434])
x.h('9. Fuentes técnicas',new=True)
for s in ['SonarSource. JavaScript/TypeScript test coverage: https://docs.sonarsource.com/sonarqube-cloud/analyzing-source-code/test-coverage/javascript-typescript-test-coverage','SonarSource. CI integration: https://docs.sonarsource.com/sonarqube-community-build/analyzing-source-code/ci-integration/overview','Postman. Newman: https://learning.postman.com/docs/reference/newman-cli/installing-running-newman/','Grafana. Umbrales k6: https://grafana.com/docs/k6/latest/using-k6/thresholds/','Render. Free services: https://render.com/docs/free','Render. Deployments: https://render.com/docs/deploys','Render. Blueprint: https://render.com/docs/blueprint-spec','Neon. PostgreSQL y plan gratuito: https://neon.com/docs/introduction/plans','Vitest. Coverage: https://vitest.dev/config/coverage','PGlite. API: https://pglite.dev/docs/api'] :x.p(s)
x.p('Consulta de fuentes técnicas: 25 de septiembre de 2026. Los límites de proveedores y las versiones pueden cambiar. Las decisiones de arquitectura son del proyecto; no constituyen una certificación de los proveedores.')
x.done()

# 04 defense
x=Doc('04_Preparacion_de_defensa.pdf','Preparación de la defensa','Pauta de práctica, demostraciones y preguntas de comprensión.','Material para practicar. No leer como guion durante la grabación.')
x.h('1. Reglas que debe cumplir cada video')
for s in ['Máximo diez minutos y un único video por fase, publicado en YouTube público o no listado.','Iniciar con nombre completo y carné. Mantener cámara encendida y rostro visible durante todo el segmento.','Demostrar en pantalla el componente, no mostrar únicamente capturas.','Al ser un solo integrante, preparar una toma continua que cubra los tres roles; confirmar con el catedrático la adaptación del equipo individual.','No leer un guion en cámara. Practicar para explicar con palabras propias.','El enlace debe permanecer accesible hasta publicación de notas. No usar modo privado.']:x.bullet(s)
x.h('2. Fase 1 · Pauta de nueve minutos',new=True)
x.table(['Tiempo','Demostración','Qué debes explicar'],[['0:00-0:40','Identificación y producto','Nombre, carné, origen con IA y problema que resuelve.'],['0:40-2:00','Aplicación desplegada','Login, catálogo y reserva; mostrar la URL pública real.'],['2:00-3:10','Requisitos y arquitectura','Cliente/servidor separados; regla 1-8 horas; actores y base.'],['3:10-5:50','Tres casos en vivo','CP-20 aprobado; CP-19 aprobado por rechazar 59 min; CP-51 fallido en baseline-v0 y corregido en versión actual.'],['5:50-7:10','Herramienta profesional','Plan, ejecución, matriz y defecto con evidencia real.'],['7:10-8:20','Métricas y limitaciones','57/60 inicial; 60/60 después; no confundir SCA con funcionales.'],['8:20-9:10','Aprendizaje y cierre','Aporte personal verificable y enlace/evidencia.']],[70,145,289])
x.p('La corrida completa ejecuta rápidamente los casos y permite mostrar CP-51 con resultado Fallido en la versión inicial. Para una demostración HTTP directa, crear dos reservas contiguas y, en la versión inicial, mantener la primera sin devolver al entregar la segunda. El reloj controlado del script evita esperar una hora. Aclarar que ese reloj se usa solo en el arnés de pruebas.')
x.h('3. Reproducir el fallo conservado',2)
x.p('Si extrajiste el ZIP sin carpeta .git, primero restaura el historial: git clone ReservaLab_historial.bundle ../ReservaLab-con-historial. Entra a esa carpeta y ejecuta los siguientes comandos. No son revisiones de PR, sino historial local real.')
x.code('git worktree add ../ReservaLab-base baseline-v0\nNew-Item -ItemType Directory -Force ../ReservaLab-base/scripts\nCopy-Item scripts/functional.mjs ../ReservaLab-base/scripts/functional.mjs -Force\ncd ../ReservaLab-base\nnpm ci\nnode scripts/functional.mjs --baseline')
x.p('La aplicación actual contiene la solución; no eliminar validaciones para simular una falla nueva. Sobre la línea base, CP-50, CP-51 y CP-59 fallan por discrepancias reales ya documentadas. Verificar previamente la reproducción y mostrar la salida original, no un archivo editado.')
x.h('4. Fase 2 · Pauta de nueve minutos',new=True)
x.table(['Tiempo','Demostración','Qué debes explicar'],[['0:00-0:40','Identificación','Nombre, carné y titularidad de los tres roles.'],['0:40-1:40','Ramas y PR','Promoción DEV->QA->main y revisión externa real/adaptación autorizada.'],['1:40-3:00','Unitarias y cobertura','Unidad aislada, mocks y alcance del 100%; comparación con base.'],['3:00-4:10','API','Flujo de 24 solicitudes; aserciones de esquema/contenido.'],['4:10-6:20','Pipeline completo','Iniciar una ejecución en vivo y mostrar sus etapas y resultado; mantener toma continua.'],['6:20-7:40','Sonar','Estado inicial/final, Blocker/Critical y gate real.'],['7:40-8:50','Carga','Perfil 50 VU/5 min, promedio/p95/throughput/error y contraste RNF.'],['8:50-9:30','Reflexión','Límites del entorno y mejoras verificables.']],[70,145,289])
x.p('El tiempo real del pipeline debe ensayarse antes. Si tarda más que el espacio disponible, consultar al catedrático cómo demostrarlo dentro del límite sin editar la toma interna ni fingir una ejecución. No sustituir una ejecución exigida en vivo por una captura o video pregrabado sin autorización.')
x.h('5. Preguntas para practicar',new=True)
qa=[('¿Por qué no basta un CRUD?','Porque se evalúan reglas entre entidades, decisiones de disponibilidad, permisos, cupos, concurrencia y transiciones.'),('¿Una respuesta 409 significa prueba fallida?','No. Si el caso esperaba rechazar un conflicto con 409, la prueba pasa. Falla cuando obtenido difiere de esperado.'),('¿Qué diferencia hay entre unitarias y API?','La unitaria aísla una función con framework/dobles; la API envía solicitudes HTTP y valida contrato/flujo entre componentes.'),('¿Qué demuestra 100% de cobertura?','Que las líneas del alcance declarado se ejecutaron; no asegura ausencia de defectos ni cobertura global de la aplicación.'),('¿Por qué se volvió a consultar disponibilidad al aprobar?','Porque entre solicitud y aprobación otra reserva puede ocupar el horario. La comprobación debe ser transaccional.'),('¿Qué causó DEF-02?','Se verificaba la ventana temporal pero no la devolución física del préstamo previo. Se agregó bloqueo del equipo y consulta de préstamo abierto.'),('¿Por qué PostgreSQL externo en cloud?','La persistencia no debe depender del disco efímero de un servicio gratuito. La base mantiene los registros entre reinicios.'),('¿Qué hace el Quality Gate?','Evalúa condiciones de calidad y bloquea el paso posterior si falla; no corrige el código por sí mismo.'),('¿Qué son promedio, p95 y throughput?','Promedio resume latencias; p95 deja el 95% de solicitudes por debajo del valor; throughput mide solicitudes por segundo.'),('¿Qué parte hiciste tú y qué hizo la IA?','Describir con honestidad la generación asistida y las tareas que realmente ejecutaste, revisaste y comprendiste; mostrar tus commits reales.')]
for q,a in qa:x.h(q,2);x.p(a)
x.h('6. Lista antes de grabar',2)
for s in ['Probar micrófono, cámara, texto legible y conexión.','Cerrar vistas de contraseñas/tokens y utilizar datos demo.','Verificar enlaces en sesión independiente.','Ensayar una toma completa menor de diez minutos.','Tener abiertas las herramientas que demostrarás; no leer este documento en cámara.','Después de subir a YouTube, revisar audio, imagen, duración y acceso no listado/público.']:x.bullet(s)
x.done()

# Two honest half-page worksheets with compact identification and index.
for num,phase,date in [('05','1','25 de septiembre de 2026'),('06','2','30 de octubre de 2026')]:
 title='Bitácora individual - Fase '+phase
 story=[para('UNIVERSIDAD MARIANO GÁLVEZ DE GUATEMALA','small'),para(title,'h1'),para('ERICK ESTUARDO CRUZ ROMERO · Carné 0900-19-1362'),para('Curso: Aseguramiento de la Calidad de Software · Entrega: '+date,'small'),para('Ficha de media página para completar con experiencia real. No acredita actividades aún no realizadas.','small'),para('Índice: producción personal · dificultades · aprendizaje · mejora','small')]
 prompts=[('Qué produje personalmente','Indicar archivos, pruebas o configuraciones que ejecuté/revisé, con fecha y commit o evidencia.'),('Qué dificultad enfrenté','Describir una dificultad concreta y cómo la resolví o por qué sigue pendiente.'),('Qué aprendí','Explicar un aprendizaje técnico que puedo demostrar sin leer.'),('Qué haría distinto','Proponer una mejora basada en lo ocurrido durante esta fase.')]
 for label,hint in prompts:story.extend([Paragraph(html.escape(label),ParagraphStyle('compact',fontName=BOLD,fontSize=9,leading=12,spaceBefore=5,spaceAfter=3,textColor=TEAL)),para(hint,'small'),para('________________________________________________________________','small')])
 file=num+'_Bitacora_Erick_Fase_'+phase+'.pdf';PDF(O/file,title).build(story);(P/'docs'/file.replace('.pdf','.md')).write_text('# '+title+'\n\nERICK ESTUARDO CRUZ ROMERO · 0900-19-1362\n\nCompletar con experiencia real.\n\n'+'\n\n'.join('## '+a+'\n'+b+'\n[Completar después de realizar la actividad]' for a,b in prompts));print(file)
